<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ListaFormularioPedidos</name>
   <tag></tag>
   <elementGuidId>cddf5798-be1c-4ac7-ae2d-0fd2f6d36783</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;header_crmFormSelector&quot;)/nobr[@class=&quot;ms-crm-FormSelector&quot;]/span[@class=&quot;ms-crm-FormSelector&quot;][count(. | //*[(text() = 'Pedido : Formulario PyP Aguas PosPago' or . = 'Pedido : Formulario PyP Aguas PosPago') and @ref_element = 'Object Repository/Page_PedidoNuevo/iframe_Abra este formulario en el editor de formularios_contentIFrame0']) = count(//*[(text() = 'Pedido : Formulario PyP Aguas PosPago' or . = 'Pedido : Formulario PyP Aguas PosPago') and @ref_element = 'Object Repository/Page_PedidoNuevo/iframe_Abra este formulario en el editor de formularios_contentIFrame0'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='header_crmFormSelector']/nobr/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-crm-FormSelector</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pedido : Formulario PyP Aguas PosPago</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header_crmFormSelector&quot;)/nobr[@class=&quot;ms-crm-FormSelector&quot;]/span[@class=&quot;ms-crm-FormSelector&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_PedidoNuevo/iframe_Abra este formulario en el editor de formularios_contentIFrame0</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='header_crmFormSelector']/nobr/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cargando la lógica de negocios...'])[1]/following::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nuevo Pedido'])[1]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cliente'])[1]/preceding::span[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nobr/span</value>
   </webElementXpaths>
</WebElementEntity>
